### ISSUE TITLE
Trouble with startup (all, including node/local, gitpod and netflify)

### ISSUE THREAD

**Issue by synedra** [DataStax-Examples/astra-gatsbyjs-starter#10]
In this file: src/pages/index.tsx

At the end it has this:
export const query = graphql`
    query getCharacters {
        astra {
            gatsby_characters {
                values {
                    actor_name
                    house_name
                    name
                }
            }
        }
    }
`;

But this requires that there be a fieldname of "astra" in the Query type, which there isn't in our schemas.
```
Also, this in the schema:
__conversionWarnings: [String]

Is causing an error from GraphQL.

Error: Name "__conversionWarnings" must not begin with "__", which is reserved   by GraphQL introspection.
8:47:20 AM:   
8:47:20 AM:   - query-compiler.js:212 extractOperations
8:47:20 AM:     [repo]/[gatsby]/src/query/query-compiler.js:212:20
8:47:20 AM:   

I've looked around in this and I can't figure out how to modify the schema so it understands astra, or remove or rename the __conversionFiles.  Can someone help with this?
```

**Comment by kidrecursive** [comment]
Heya, it looks like the query in `index.ts` needed to be updated, I took care of that and updated it in the master branch. Thanks for pointing this out!
